#ifndef ESP32S3_H
#define ESP32S3_H

#include <stdint.h>
#include "main.h"        /* UART_HandleTypeDef (for *_UART_RxCallback signature) */
#include "usart.h"       /* huart6 (extern handle declaration, generated by CubeMX) */
#include "cmsis_os2.h"   /* osMessageQueueId_t */

#ifdef __cplusplus
extern "C" {
#endif

/* =============================================================================
 * ESP32-S3 CAM image co-processor comms (STM32 H743 RX side)
 * -----------------------------------------------------------------------------
 * Physical link : USART6 (PC6=TX->ESP32 RX cmd, PC7=RX<-ESP32 TX image result), 921600
 * Frame format  : see Pinout Sec.12.6 -- header AA 55 + len L(1B) + CMD(1B) + payload(L-1 B) + CRC16(2B, low byte first)
 * RX mechanism  : HAL_UARTEx_ReceiveToIdle_IT (IDLE IRQ frames, no DMA; small FOMO frame rate is enough, avoids DMA2 config)
 * Debug scheme  : unified LOG_I("ESP32", ...) (task context only, never in ISR), verified via UART1 to PC
 *                 -- identical to Components/Debug DBG_LOG_<TASK> scheme; ISR only does "frame RX + enqueue + set flag".
 *
 * Consumer model: parse task (this module) is sole consumer of Queue_ImgResult, writes s_latest snapshot and logs;
 *                 other tasks (fault-diag/control) read snapshot via ESP32S3_GetLatest().
 * ============================================================================= */

#define ESP32S3_MAX_OBJ       8       /* Max objects per frame */
#define ESP32S3_RX_BUF_SIZE   256     /* ReceiveToIdle_IT RX buffer (single frame far smaller) */
#define ESP32S3_Q_DEPTH       8       /* Image result queue depth */
#define ESP32S3_SYNC_H1       0xAA
#define ESP32S3_SYNC_H2       0x55

/* CMD list (must match ESP32 firmware) */
#define ESP32S3_CMD_DETECT    0x01    /* Detect result frame: payload = N(1B) + N x (cls(1B)+cx(2B,0~1000)+cy(2B,0~1000)+conf(1B,0~100)) */

/* Single object (normalized center x1000, matches Pinout Sec.12.6) */
typedef struct {
    uint8_t  cls;     /* Class ID */
    uint16_t cx;      /* Normalized center x x1000 (0..1000) */
    uint16_t cy;      /* Normalized center y x1000 (0..1000) */
    uint8_t  conf;    /* Confidence 0..100 */
} esp32s3_obj_t;

/* One-frame detect result snapshot */
typedef struct {
    uint8_t        count;      /* Object count in this frame */
    esp32s3_obj_t  obj[ESP32S3_MAX_OBJ];
    uint32_t       frame_cnt;  /* Global frame seq (auto-inc, for VOFA/log compare) */
} esp32s3_result_t;

/* Image result queue (CubeMX-generated g_ImgResultImg_qHandle, Size=8/ItemSize=72).
 * Consumed by this module's parse task; other tasks read ESP32S3_GetLatest snapshot. */
extern osMessageQueueId_t g_ImgResultImg_qHandle;

/* CubeMX-generated task handle (wake from ISR via osThreadFlagsSet). */
extern osThreadId_t Task_Esp32S3Handle;

/* Parse task entry: called by CubeMX-generated StartEsp32S3Task.
 * Task creation is CubeMX's job; this module only provides the implementation. */
void ESP32S3_Task_Run(void *argument);

/* Init: create queue + force USART6 baud 921600.
 * Must be called inside MX_FREERTOS_Init() (CubeMX USER CODE BEGIN Init), before osKernelStart().
 * Task (Task_Esp32S3) is created by CubeMX separately. */
int ESP32S3_BSP_Init(void);

/* Get latest frame result snapshot (copy out, caller reads on demand, non-blocking) */
int ESP32S3_GetLatest(esp32s3_result_t *out);

/* Debug cmd 'X': print RX stats (frame count / CRC err / last frame) via UART1 */
void ESP32S3_PrintStats(void);

/* Get total valid frames received since boot (for POST/runtime link health check).
 * POST 期恒为 0（ESP32-S3 尚未发帧/未接）；运行期由 ISR 递增。 */
uint32_t ESP32S3_GetFrameCount(void);

/* Runtime link validation flag: set true once >=1 valid frame received.
 * FSM/其它任务可据此判断是否具备目标检测输入（false 且过启动窗口 = 降级）。 */
uint8_t  ESP32S3_IsLinkValidated(void);

/* USART6 IDLE RX callback (forwarded by HAL_UARTEx_RxEventCallback in Components/BSP/uart_rx_dispatcher.c;
 * ISR context). */
void ESP32S3_UART_RxCallback(UART_HandleTypeDef *huart, uint16_t size);

/* Re-arm USART6 RX after an error (called from Components/BSP/uart_rx_dispatcher.c
 * error recovery). Returns HAL status; safe in ISR context. */
HAL_StatusTypeDef ESP32S3_UART_RxStart(void);

/* POST ESP32-S3 自检入口（按 APP_ENABLE_ESP32S3 门控）：驱动/软件链路校验（非线缆）。
 * 实现见 esp32s3.c 尾部。 */
int Esp32S3_Test(void);

#ifdef __cplusplus
}
#endif

#endif /* ESP32S3_H */
